feature_list = [
    "Shares",
    "Returns",
    "Beta to J203",
    "Beta to USDZAR",
    "Beta to RBAS",
    "Beta to RLRS",
    "Beta to FSPI",
    "Specific Risk",
    "Debt to Equity",
    "Debt to Equity Trend",
    "Interest Cover Trend",
    "log Market Cap",
    "log Trading Volume",
    "Earnings Yield",
    "Earnings Yield Trend",
    "Bookvalue to Price",
    "Bookvalue to Price Trend",
    "Dividend Yield",
    "Dividend Yield Trend",
    "Cashflow to Price",
    "Cashflow to Price Trend",
    "Sales to Price",
    "Sales to Price Trend",
    "Profit Margin",
    "Capital Turnover",
    "Capital Turnover Trend",
    "Return on Assets",
    "Return on Assets Trend",
    "Return on Equity",
    "3 Month Return",
    "6 Month Return",
    "12 Month Return",
    "24 Month Return",
    "36 Month Return",
    "Resource",
    "Financial"
]
